export const states = {

    GET_DATA: "GET_DATA",
    RESET_DATA: "RESET_DATA",
    INPUT_VALUES: "INPUT_VALUES",
    CONFIRM_RENTAL: "CONFIRM_RENTAL",
    SHOW_ALERT: "SHOW_ALERT",
    HIDE_ALERT: "HIDE_ALERT",
    TXT_ALERT: "TXT_ALERT"
};